language: C
install:
  - sudo apt-get update -qq -y
  - sudo apt-get install chicken-bin libatlas3-base libatlas-base-dev libatlas-dev
script: 
  - chicken -version
  - chicken-install -s -test
  - csi -s tests/run.scm

